export const labelsTypes = {
  ADD_LABEL: 'ADD_LABEL',
  DELETE_LABEL: 'DELETE_LABEL',
  MODIFY_LABEL: 'MODIFY_LABEL',
};

export const todosTypes = {
  CREATE_TODO: 'CREATE_TODO',
  TOGGLE_TODO_DONE: 'TOGGLE_TODO_DONE',
  DELETE_TODO: 'DELETE_TODO',
  DELETE_NON_EXISTING_LABEL_IDS: 'DELETE_NON_EXISTING_LABEL_IDS',
};

export const modalTypes = {
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
};
