export const labelsTypes = {
  SET_LABELS: 'SET_LABELS',
  CREATE_LABEL: 'CREATE_LABEL',
  DELETE_LABEL: 'DELETE_LABEL',
  MODIFY_LABEL: 'MODIFY_LABEL',
};

export const todosTypes = {
  SET_TODOS: 'SET_TODOS',
  CREATE_TODO: 'CREATE_TODO',
  TOGGLE_TODO_DONE: 'TOGGLE_TODO_DONE',
  DELETE_TODO: 'DELETE_TODO',
  MODIFY_TODO_LABELS: 'MODIFY_TODO_LABELS',
  DELETE_NON_EXISTING_LABEL_IDS: 'DELETE_NON_EXISTING_LABEL_IDS',
};

export const groupsTypes = {
  SET_TODO_GROUPS: 'SET_TODO_GROUPS',
  CREATE_TODO_GROUP: 'CREATE_TODO_GROUP',
  SELECT_TODO_GROUP: 'SELECT_TODO_GROUP',
};

export const modalTypes = {
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
};

export const notificationTypes = {
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
};
