export const labelsTypes = {
  ADD_LABEL: 'ADD_LABEL',
  DELETE_LABEL: 'DELETE_LABEL',
  MODIFY_LABEL: 'MODIFY_LABEL',
};

export const todosTypes = {
  CREATE_TODO: 'CREATE_TODO',
  TOGGLE_TODO_DONE: 'TOGGLE_TODO_DONE',
  DELETE_TODO: 'DELETE_TODO',
};
